name: binderpycourse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - numpy=1.22.3
  - xarray=2022.3.0
  - netcdf4=1.5.8
  - matplotlib=3.5.1
  - cartopy=0.18.0
  - pandas=1.5.3
  - seaborn=0.13.0
  - eccodes=2.26.0
  - cfgrib=0.9.10.4
  - scipy=1.11.2
